### ISSUE TITLE
Implementing Onvif discovery in windows?

### ISSUE THREAD

**Issue by ahasan016** [caspermeijn/kdsoap-ws-discovery-client#5]
is it possible to use your project in windows? I want to include onvif discovery feature in a visual studio project of mine in windows. please let me know if it is possible. or any idea how to do it?

**Comment by caspermeijn** [comment]
Hi, I don't use Windows, so I have not tried. I think you should include the CMake project. Maybe this will help: https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019

But I have not tested the library on Windows, so you could find bugs.

**Comment by caspermeijn** [comment]
The project is moved to https://invent.kde.org/libraries/kdsoap-ws-discovery-client
Please open an issue there if you are still interested
